#!/usr/bin/env python3

import json
import requests


html = '''
<html>
    <body>
        <table>
            <th><td>Repository</td><td>Private?</td><td>SSH key</td></th>
'''

with open('/root/.github-api-token') as f:
    token = f.readlines()[0].strip()

# Check for invitations
url = 'https://api.github.com/user/repository_invitations?access_token=%s' % token
r = requests.get(url)
for invitation in r.json():
    url = 'https://api.github.com/user/repository_invitations/%d?access_token=%s' % (invitation['id'], token)
    r = requests.patch(url)
    print('Accepted invitation to %s' % invitation['repository']['full_name'])

# Check for repositories
url = 'https://api.github.com/user/repos?access_token=%s' % token
r = requests.get(url)
for repo in r.json():
    #print(json.dumps(repo, indent=2, sort_keys=True))

    # Skip own repos
    if repo['owner']['login'] in ['ICA0002-bot']:
        continue

    repo_html = '<td>%s</td>' % repo['full_name']

    if repo['private']:
        repo_html += '<td class="ok">Yes</td>'
    else:
        repo_html += '<td class="fail">No</td>'

    # Check for user SSH keys
    key_url = '%s.keys' % repo['owner']['html_url']
    r = requests.get(key_url)
    if r.text.startswith('ssh-'):
        repo_html += '<td class="ok">Added</td>'
    else:
        repo_html += '<td class="fail">Missing</td>'

    html += '<tr>%s</tr>' % repo_html

html += '''
        </table>
    </body>
</html>
'''

with open('/opt/ica0002/pub/index.html', 'w') as f:
    f.write(html)
