#!/bin/sh -eu

expected_files=$(cat <<EOF
ansible.cfg:lab-1,lab-2,lab-3,lab-4,lab-5,lab-6,lab-7,lab-8
backup_restore.md:lab-10
backup_sla.md:lab-9,lab-10
grafana_dashboard.json:lab-7,lab-8,lab-11
group_vars/all.yaml:lab-4,lab-5,lab-6,lab-7,lab-8
hosts:lab-1,lab-2,lab-3,lab-4,lab-5,lab-6,lab-7,lab-8
lab02_web_server.yaml:lab-2
lab03_web_app.yaml:lab-3
lab04_web_app.yaml:lab-4
lab05_dns.yaml:lab-5
lab06_prometheus.yaml:lab-6
lab07_grafana.yaml:lab-7
lab08_logging.yaml:lab-8
lab09_backups.yaml:lab-9
lab10_backups.yaml:lab-10
lab11_mysql_ha.yaml:lab-11
roles/agama/tasks/main.yaml:lab-3
roles/backup/tasks/main.yaml:lab-9,lab-10
roles/bind/tasks/main.yaml:lab-5,lab-6
roles/bind_exporter/tasks/main.yaml:lab-7
roles/grafana/tasks/main.yaml:lab-7
roles/influxdb/tasks/main.yaml:lab-8
roles/mysql/tasks/main.yaml:lab-4,lab-11
roles/mysql_exporter/tasks/main.yaml:lab-7
roles/nginx/tasks/main.yaml:lab-2,lab-3
roles/nginx_exporter/tasks/main.yaml:lab-7
roles/pinger/tasks/main.yaml:lab-8
roles/rsyslog/tasks/main.yaml:lab-8
roles/prometheus/tasks/main.yaml:lab-6
roles/users/tasks/main.yaml:lab-2
roles/uwsgi/tasks/main.yaml:lab-3
EOF
)

known_service_url_paths=$(cat <<EOF
Wep_app_(labs_3,_4,_7)::1
Grafana_(lab_7):/grafana:1
Prometheus_(labs_6,_7):/prometheus:1
Bind_metrics_(lab_7):/bind-metrics:1
MySQL_metrics_(labs_7,_11):/mysql-metrics:2
Nginx_metrics_(lab_7):/nginx-metrics:2
Node_metrics_(labs_6,_7):/metrics:2
EOF
)

check_student() {
    student="$1"
    student_vm_ips=$(echo "$2" | sed 's/,/ /g')
    student_vm_urls=$(echo "$student_vm_ips" | sed -E 's|192.168.42.([0-9]+)|http://193.40.156.86:\180|g')

    labs_not_done=""
    repo="/opt/ica0002/data/students/$student/git"
    result=true

    html=$(cat <<EOF
<html>
    <head>
        <title>$student - ICA0002 2020</title>
        <link rel="stylesheet" type="text/css" href="/style.css">
    </head>
    <body>
        <a href="/">ICA0002 2020</a> &raquo; <a href="/students.html">Students</a> &raquo; <a href="/results/$student.html">$student</a>
        <h1>$student</h1>
        <h3>
          Note: this page is generated by script that is still being tested.
          If you feel that something is not quite right here please contact the teachers.
        </h3>
EOF
    )
    echo "---"
    echo "Student: $student"
    echo "URL: http://193.40.156.86/results/$student.html"

    # List services
    html="$html\n<h2>Services</h2>\n<table>"
    for service in $known_service_url_paths; do
        service_state="fail"
        service_name=$(echo "$service" | cut -d: -f1 | tr '_' ' ')
        service_path=$(echo "$service" | cut -d: -f2)
        service_count_expected=$(echo "$service" | cut -d: -f3)
        service_count_actual=0
        service_urls=$(echo "$student_vm_urls" | sed -E "s|(:[0-9]+80)|\1$service_path|g")

        html="$html\n<tr><td>$service_name</td>"
        urls_up=""
        urls_down=""
        if [ -n "$service_urls" ]; then
            for service_url in $service_urls; do
                http_status=$(get_http_status_code "$service_url")
                if [ "$http_status" -eq 200 ]; then
                    urls_up="$urls_up, <a href=\"$service_url\">$service_url</a>"
                    service_count_actual=$((service_count_actual + 1))
                else
                    urls_down="$urls_down, <a href=\"$service_url\">$service_url</a> -- <span class=\"fail\">HTTP $http_status</span>"
                fi
            done
        else
            urls_down="---"
        fi
        urls_up=$(echo "$urls_up" | sed 's/^, //')
        urls_down=$(echo "$urls_down" | sed 's/^, //')

        if [ "$service_count_actual" -ge "$service_count_expected" ]; then
            html="$html\n<td>$urls_up</td>"
            html="$html\n<td class=\"ok\">$service_count_actual/$service_count_expected up</td></tr>"
        else
            html="$html\n<td>$urls_down</td>"
            html="$html\n<td class=\"fail\">$service_count_actual/$service_count_expected up</td></tr>"
        fi
    done
    html="$html\n</table>"

    echo "Git repository checks:"
    html="$html\n<h2>Git repository checks</h2>\n<ul>"

    # Check repository
    if grep -q "^$student/" /opt/ica0002/data/ready-repos.txt; then
        html="$html\n$(html_ok GitHub repository is set up correctly.)"
        print_ok "GitHub repository is set up correctly"
    else
        html="$html\n$(html_fail GitHub repository is not ready: either not private or public key missing.)"
        print_fail "GitHub repository is not ready: either not private or public key missing"
        result=false
    fi

    # Check files
    if [ -d "$repo" ]; then
        for f in $expected_files; do
            file=$(echo "$f" | cut -d: -f1)
            labs=$(echo "$f" | cut -d: -f2)
            if [ -f "$repo/$file" ]; then
                html="$html\n"$(html_ok "<code>$file</code> found.")
                print_ok "$file found"
            else
                labs_formatted=$(format_lab_list "$labs")
                html="$html\n"$(html_fail "<code>$file</code> is missing; labs not accepted: $labs_formatted.")
                print_fail "$file is missing; labs not accepted: $labs_formatted"
                labs_not_done="$labs_not_done,$labs"
                result=false
            fi
        done
    else
        html="$html\n"$(html_fail "Could not check your repository at this time. Please re-check this page tomorrow. If there are still no results, please contact the teachers.")
        result=false
        print_fail "Local repository not found: $repo"
    fi

    html="$html\n</ul>\n"

    # Print summary
    if [ "$result" = true ]; then
        html="$html\n<p>All good do far.</p>"
        echo "All good."
    else
        html="$html\n<p>A few problems found.</p>"
        echo "A few problems found."
    fi

    if [ -n "$labs_not_done" ]; then
        labs_formatted=$(format_lab_list $labs_not_done)
        html="$html\n<p>Labs not accepted: $labs_formatted.</p>"
        echo "Labs not accepted: $labs_formatted"
    fi

    html="$html\n<p>Last checked on $(date +'%b %d at %R UTC').</p>\n</body></html>"
    echo "$html" > "/opt/ica0002/pub/results/$student.html"
}

get_http_status_code() {
    case "$1" in
    */prometheus) curl -s -L -o/dev/null -w"%{http_code}" "$1" || echo 0 ;;
    *) curl -s -I -L -o/dev/null -w"%{http_code}" "$1" || echo 0 ;;
    esac
}

get_vms() {
    /usr/local/bin/vm-admin all | grep 192.168.42 | awk '{print $3":"$2}'
}

format_lab_list() {
    echo "$@" | sed 's/lab-//g;' | tr -d ' ' | xargs -d, -n1 | sort -hu | grep . | paste -sd, | sed 's/,/, /g'
}

html_fail() {
    echo "<li><span class=\"fail\">Problem</span>: $@</li>"
}

html_ok() {
    echo "<li><span class=\"ok\">Ok</span>: $@</li>"
}

print_fail() {
    echo " [\033[0;31mfail\033[0m] $@"
}

print_ok() {
    echo " [\033[0;32mok\033[0m] $@"
}


echo "Gathering data..."
vms=$(get_vms)

for i in $(cat /opt/ica0002/data/known-students.txt); do
    student_vm_ips=$(echo "$vms" | grep ":$i-" | cut -d: -f1 | paste -sd,)
    check_student "$i" "$student_vm_ips"
done
